### PR TITLE
2 feature 2 create course entity layer class

### PR DESCRIPTION
**Pull request by realdevvora**

### CODE REVIEW

**Review by uyoyo0 — DISMISSED** [review]
Looks good

**Review by JaspreetKhela — CHANGES_REQUESTED** [review]
Please add comments to your code. Everything else looks good.

**Review by LVaishno — COMMENTED** [review]
Everything seems to make sense

**Review by M4N4VS1NGH — COMMENTED** [review]
Good changes, I think this should be good.

**Review by LVaishno — APPROVED** [review]
Approved

**Review by JaspreetKhela — APPROVED** [review]

**Review by uyoyo0 — APPROVED** [review]
Looks even better with the comments

**Pull request merged**
