### PR TITLE
Update UserDB and interfaces to adhere to Clean

### PR DESCRIPTION
**Pull request by realdevvora**
I added the dependency injection design pattern into the UserDB class so that the interfaces provide the functionalities of the database rather than having a hard dependency on the actual userDB class.

### CODE REVIEW

**Review by LVaishno — DISMISSED** [review]
Edits make sense

**Review by uyoyo0 — APPROVED** [review]
Looks good overall, I added a couple of additional changes.

**Review by M4N4VS1NGH — APPROVED** [review]
These are great updates to adhere to clean architecture.

As for the UserDB class, I believe you did a good job with handling the reading and writing of user data into the database. I also like the fact that we've implemented email and username uniqueness checkers. For later versions, you could include some sort of password hashing technique so that there would be no security risks. Make sure you have some way that would allow the application to have access to the path file as well, otherwise you should handle the situation wherein the application lacks permission.

Overall, this is a good update.

**Review by LVaishno — APPROVED** [review]
The modifications look good

**Pull request merged**
