### PR TITLE
added the methods and attributes for methods im responsible for

### PR DESCRIPTION
**Pull request by uyoyo0**

### CODE REVIEW

**Comment by realdevvora** [comment]
For pull requests in the future, make sure to break each issue into a separate pull request rather than several files at the same time. I know you probably did this because you are just adding methods for interfaces, but just in case you don't know this. Other than that, it's good.

**Review by realdevvora — DISMISSED** [review]
👍

**Comment by JaspreetKhela** [comment]
Please add comments to your code. Otherwise, everything looks good.

**Review by JaspreetKhela — CHANGES_REQUESTED** [review]
Please add comments to your code. Otherwise, everything looks good.

**Review by GagandeepLubana — DISMISSED** [review]

**Review by realdevvora — DISMISSED** [review]
👍

**Pull request closed without merging**
