### PR TITLE
Create Program entity

### PR DESCRIPTION
**Pull request by realdevvora**

### CODE REVIEW

**Review by uyoyo0 — APPROVED** [review]
Looks good

**Review by JaspreetKhela — CHANGES_REQUESTED** [review]
Please add comments to your code. Everything else looks good.

**Review by LVaishno — COMMENTED** [review]
Everything looks fine to me

**Review by M4N4VS1NGH — APPROVED** [review]
Great work

**Review by LVaishno — APPROVED** [review]
Approved

**Review by JaspreetKhela — APPROVED** [review]

**Pull request merged**
