### PR TITLE
135 enhancement 1 enhance and reformat recommendation algorithm

### PR DESCRIPTION
**Pull request by uyoyo0**
Several changes were made to both improve our recommendation algorithms and to promote CA
- Used additional data from survey to improve the accuracy of RecommendationAlgorithm
- Made Program comparable and added a relevance attribute to facilitate the sorting 
- Made RecommendationAlgorithm and ExtractCoursesRecommendations implement ExtractCoursesRecommendationsInterface to facilitate interfacing
- Made ExtractProgramRecommendations implement ExtractProgramRecommendationsInterface to faciliatate interfacing 
- Modified CarouselPresenter to reflect these changes

### CODE REVIEW

**Review by M4N4VS1NGH — APPROVED** [review]
It's good that you updated the Program class by adding in a parameter so we can make more use of the data we've taken, and showing consistency with this change by implementing the same changes onto the Type Program interfaces.

**Review by realdevvora — APPROVED** [review]
Well documented and follows clean and SOLID properly (other than the changes that still need to be made) 👏👏👍

**Review by LVaishno — DISMISSED** [review]
The changes look good and no violations of CA or SOLID

**Review by LVaishno — APPROVED** [review]

**Review by GagandeepLubana — APPROVED** [review]
This update provides some great documentation and helps with the project structure in terms of CA and SOLID design. Looks good to me 👍.

**Review by realdevvora — APPROVED** [review]

**Pull request merged**
