### PR TITLE
Implement GETProgramGateway

### PR DESCRIPTION
**Pull request by M4N4VS1NGH**

### CODE REVIEW

**Review by realdevvora — APPROVED** [review]
Notes for future:

1. Add interfaces for this database to support extension later on (if we ever change the databasing from a text file to an actual SQL database)
2. Try to shorten the length of getProgramsListData because it is an awfully long method (maybe move the internal function outside)

**Review by uyoyo0 — APPROVED** [review]
Looks good, I second the tips that Dev left for you

**Comment by realdevvora** [comment]
> Notes for future:
> 
> 1. Add interfaces for this database to support extension later on (if we ever change the databasing from a text file to an actual SQL database)
> 2. Try to shorten the length of getProgramsListData because it is an awfully long method (maybe move the internal function outside)

For instance, you could consider adding some of the methods into the RecommendationAlgorithm interfaces and depending on those instead. This would be sufficient to migrate the database going forward.

**Review by JaspreetKhela — APPROVED** [review]
Your work looks great overall! 

In particular, I like that you separated the CSV parsing functionality into a separate method; this prevents the duplication of code elsewhere in this file if additional methods are added down the line. However, you should place the CSV file-reading part of your code in a CSV files-specific method since we want the 'getProgramsListData' method to work with all types of web APIs, files, and databases; it should only contain control flow statements directing the program to read or retrieve data from the appropriate source. In other words, we want to eliminate the need to modify our methods down the line in the spirit of the Open/Closed SOLID Design Principle.

Additionally, I was confused by your use of an ArrayList instead of a HashMap to store programs that you read from the CSV file; this may become an issue down the line with regard to efficiently searching for programs within a data structure and storing content stored within a data structure to a database. Specifically, in reference to the latter point, since HashMap keys are unique within the HashMap data structure, these keys may easily be used as unique identifiers for programs' data within database tables/documents. Additionally, we want to reduce modification of code down the line by considering these design tradeoffs ahead of time, such as choosing a HashMap instead of an ArrayList data structure to store programs' data. Again, this is in the spirit of the Open/Closed SOLID Design Principle.

Lastly, adding comments for each part of a control flow statement (e.g. for the 'if', 'else if', 'else', etc.) would help in improving the readability of your code.

**Pull request merged**
